module.exports = {
    SCORE_INCREASE_BY_1: 'SCORE_INCREASE_BY_1',
    SCORE_AUTO_INCREASE_1_PER_SEC: 'SCORE_AUTO_INCREASE_1_PER_SEC',
    SCORE_AUTO_INCREASE_5_PER_SEC: 'SCORE_AUTO_INCREASE_5_PER_SEC'
};